apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: aerospike-data-pvc
  namespace: aerospike
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: local-ssd

