apiVersion: asdb.aerospike.com/v1
kind: AerospikeCluster
metadata:
  name: aerocluster
  namespace: aerospike

spec:
  size: 2
  image: aerospike/aerospike-server-enterprise:6.3.0.28

  podSpec:
    multiPodPerHost: true

  storage:
    filesystemVolumePolicy:
      cascadeDelete: true
      initMethod: deleteFiles
    volumes:
      - name: workdir
        source:
          persistentVolume:
            storageClass: local-ssd
            volumeMode: Filesystem
            size: 3Gi
        aerospike:
          path: /opt/aerospike

      - name: aerospike-config-secret
        source:
          secret:
            secretName: aerospike-secret
        aerospike:
          path: /etc/aerospike/secret

  aerospikeConfig:
    service:
      feature-key-file: /etc/aerospike/secret/features.conf

    network:
      service:
        port: 3000
      heartbeat:
        mode: mesh
        port: 3002
      fabric:
        port: 3001

    namespaces:
      - name: test
        replication-factor: 2
        memory-size: 1073741824  # 1 GiB
        storage-engine:
          type: memory
