apiVersion: asdb.aerospike.com/v1
kind: AerospikeCluster
metadata:
  name: aerocluster
  namespace: aerospike

spec:
  size: 2  # Number of nodes in the cluster
  image: aerospike/aerospike-server-enterprise:6.3.0.28

  rackConfig:
    namespaces:
      - aerospike
    racks:
      - id: 1
        zone: rack-1
      - id: 2
        zone: rack-2

  storage:
    filesystemVolumePolicy:
      cascadeDelete: true
      initMethod: deleteFiles
    blockVolumePolicy:
      cascadeDelete: true
    volumes:
      - name: workdir
        aerospike:
          path: /opt/aerospike
        source:
          persistentVolume:
            storageClass: local-ssd
            volumeMode: Filesystem
            size: 1Gi

      - name: ns
        aerospike:
          path: /dev/xvdf
        source:
          persistentVolume:
            storageClass: local-ssd
            volumeMode: Block
            size: 5Gi

      - name: aerospike-config-secret
        aerospike:
          path: /etc/aerospike/secret
        source:
          secret:
            secretName: aerospike-secret

  podSpec:
    multiPodPerHost: false

  aerospikeConfig:
    service:
      feature-key-file: /etc/aerospike/secret/features.conf

    network:
      service:
        port: 3000
      heartbeat:
        port: 3002
      fabric:
        port: 3001

    namespaces:
      - name: aerospike  # Device-based namespace
        replication-factor: 2
        memory-size: 2147483648  # 2GiB in bytes
        storage-engine:
          type: device
          devices:
            - /dev/xvdf

      - name: aerospikeMem  # Memory-based namespace
        replication-factor: 1
        memory-size: 1073741824  # 1GiB in bytes
        storage-engine:
          type: memory

